---

- name: repositories > From preferences pass 1
  set_fact:
    _elao_apt_preferences_repositories_item: "{{ (item.split('@')[1]).split(':')[0] }}"
  with_items: elao_apt_preferences
  when: item is string
  register: _elao_apt_preferences_repositories_pass

- name: repositories > From preferences pass 2
  set_fact:
    _elao_apt_preferences_repositories: "{{ _elao_apt_preferences_repositories_pass.results|rejectattr('skipped', 'defined')|map(attribute='ansible_facts._elao_apt_preferences_repositories_item')|list|unique }}"
  when: _elao_apt_preferences_repositories_pass.results is defined

- name: repositories > Keys
  apt_key:
    url:   "{{ item.key.url }}"
    id:    "{{ item.key.id }}"
    state: "{{ item.state|default('present') }}"
  with_items: "{{ elao_apt_repositories|select('mapping')|list }}"
  when: item.key is defined

- name: repositories > Sources
  apt_repository:
    repo:         "{{ item.source }}"
    state:        "{{ item.state|default('present') }}"
    update_cache: yes
  with_items: "{{ elao_apt_repositories|select('mapping')|list }}"

- name: repositories > Patterns keys
  apt_key:
    url:   "{{ elao_apt_repositories_patterns[item.split('/')[0]].key.url }}"
    id:    "{{ elao_apt_repositories_patterns[item.split('/')[0]].key.id }}"
    state: "{{ item.split('/')[1]|default('present') }}"
  with_items: "{{ (_elao_apt_preferences_repositories|default([]) + elao_apt_repositories|select('string')|list)|unique }}"
  when: elao_apt_repositories_patterns[item.split('/')[0]].key is defined

- name: repositories > Patterns sources
  apt_repository:
    repo:         "{{ elao_apt_repositories_patterns[item.split('/')[0]].source }}"
    state:        "{{ item.split('/')[1]|default('present') }}"
    update_cache: yes
  with_items: "{{ (_elao_apt_preferences_repositories|default([]) + elao_apt_repositories|select('string')|list)|unique }}"
