---

dependencies: []

galaxy_info:

  author:              Elao
  company:             Elao
  description: >
    Sudo is a program for Unix-like computer operating systems that allows users to run programs with the security privileges of another user.
    This role will assume the basic installation of sudo
  license:             MIT
  min_ansible_version: 1.7.2
  platforms:
    - name: Debian
      versions:
        - wheezy
        - jessie
    - name: Ubuntu
      versions:
        - trusty
  categories:
    - system
    - security