---

dependencies: []

galaxy_info:

  author:              Elao
  company:             Elao
  description: >
    Alternatives
  license: MIT
  min_ansible_version: 1.7.2
  platforms:
    - name: Debian
      versions:
        - wheezy
    - name: Ubuntu
      versions:
        - trusty
  categories:
    - development
    - web
